# Generated by Django 4.2.5 on 2024-06-14 20:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wikinow', '0002_entry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
